### ISSUE TITLE
Support for linux

### ISSUE THREAD

**Issue by zhengyangliu** [openblockcc/openblock-desktop#52]
Considering that many students in the global education field are using chromebooks, we need to make openblock run on linux systems.

## Task list:

- [x] openblockcc/openblock-tools#1
- [x] openblockcc/openblock-driver#1
- [x] openblockcc/openblock-desktop#55
- [x] #56

**Comment by soiamsoNG** [comment]
Will prefer to build a flatpak? and upload to flathub?

**Comment by zhengyangliu** [comment]
> flatpak

Don't consider building flatpak for now, it will be released using the deb package for now.

**Comment by zhengyangliu** [comment]
The linux version has been released in [OpenBlock Desktop v2.4.0](https://github.com/openblockcc/openblock-desktop/releases/tag/v2.4.0)
