### ISSUE TITLE
Automatically package and publish tools and driver packages

### ISSUE THREAD

**Issue by zhengyangliu** [openblockcc/openblock-desktop#57]
In order to prevent someone from intentionally bringing in virus files during manual packaging, or causing errors due to someone's operation, we need to change the openblock-tools and drivers packaging process to use github action to automate.

## Task list

- [ ] Automate packaging and publishing tools and add the checksum file
- [ ] Automate packaging and publishing drivers and add the checksum file
- [ ]  Modify the tools and drivers download scripts, automatically download and verify the compressed package, and then extract it to the specified directory.
